name: Custom Action Workflow

on:
  push:
    paths:
      - 'custom-action-demo/**'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Custom Action (Hello World)
        uses: tanvir039/custom-action-demo@main
        with:
          who-to-greet: "Tanvir"